version: "3.7"

services:
    consumer:
        image: postgres
        container_name: database_consumer
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=cuser
            - POSTGRES_PASSWORD=cpassword
            - POSTGRES_DB=consumer