version: "3.7"

services:
    order:
        image: postgres
        container_name: database_order
        restart: always
        ports: 
            - 5434:5432
        environment:
            - POSTGRES_USER=ouser
            - POSTGRES_PASSWORD=opassword
            - POSTGRES_DB=order