version: "3.7"

services:
    course:
        image: postgres
        container_name: database_course
        restart: always
        ports: 
            - 5433:5432
        environment:
            - POSTGRES_USER=couser
            - POSTGRES_PASSWORD=copassword
            - POSTGRES_DB=course